Prevent crash cause by a connection timeout.
+ Error:
  parsers/recent_changes_html_parser.py", line 59, in __init__
    schedule_data = urllib.request.urlopen(url)
  urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>